### ISSUE TITLE
User Hours Volunteer

### ISSUE THREAD

**Issue by VasPug** [hack4impact-calpoly/slo-beaver-brigade#115]
**Description**
Hey Jason. This issue is very similar to the admin panel hours volunteer page you already created. All you need to do is change the information received in the table to be specific to the current signed in user and add all the hours they volunteered. Add the same filters/search/etc features you had for the admin side into this. 
**Acceptance Criteria**
Looks similar to the image below. But the filters/search/etc can look the same as the admin panel ones you created. The data table needs to show the hours the user volunteered and display the sum in the card above.

**Additional Information**
<img width="753" alt="Screenshot 2024-04-27 at 1 24 30 PM" src="https://github.com/hack4impact-calpoly/slo-beaver-brigade/assets/79773179/eaaf04da-b5fe-47a4-b093-ed4eb6509b21">

**Comment by SilveerDusk** [comment]
@VasPug... you might want to check out localhost/hours 😉. I did both at the same time! I can definitely update it to match the photo more and there are some aspects of the last issue that I would like to keep working on!
