### ISSUE TITLE
BugFix Events not loading in after signup

### ISSUE THREAD

**Issue by VasPug** [hack4impact-calpoly/slo-beaver-brigade#149]
**Description**
When a user signs up for an event through the dashboard and is then redirected back to the dashboard, the events fail to load in. They only load in when the page is reloaded. 

**Acceptance Criteria**
Make the events load in properly after the user signs up for an event and gets sent back to the dashboard. 
DO NOT manually reload page. Figure out what is causing user to not be loaded into dashboard.

**Comment by spaykel** [comment]
I think someone fixed this already lol
