### ISSUE TITLE
Connect Cancel Event to Backend

### ISSUE THREAD

**Issue by VasPug** [hack4impact-calpoly/slo-beaver-brigade#48]
Description
Your task is to connect the cancel event component to the backend, ONLY do this if the form validation issue has been completed.

Steps:

Pretty straight forward, you will pass the object that the form has given you and make a fetch request to the API endpoint associated with DELETE Events.

**Comment by spaykel** [comment]
Made commits to my branch, not ready to create pull request yet, will be finishing soon
