### ISSUE TITLE
Reformat Existing Calendar

### ISSUE THREAD

**Issue by javalosr2004** [hack4impact-calpoly/slo-beaver-brigade#64]
**Description**
Your task is to change the layout of the existing calendar to more match what the designers have intended, below is a screenshot of the new calendar. Don't create a mini-calendar, we already have one that hasn't been merged yet, let me know if you get to that part and the component still isn't in the components folder. Don't worry about implementing the actual filters yet. 

**Acceptance Criteria**
Have a page that looks like the screenshot below. Be mobile friendly.

Steps:
- Use `/calendar` route as base page.
- Modify the existing **change month** icons to be directly by the side of the month, as shown in the picture.
- Disable day view / weekly view.
- Add column to the left of calendar (more info below)
- Create "filters", which are going to use <Checkbox> compoent from [Chakra UI](https://chakra-ui.com/docs/components/checkbox).

**Additional Information**
Just some advice, I believe a good way of going about this would be to have a div that contains both the calendar and the column beside it, and use flex-col and all the other flex css properties as a way to have them as separate columns, also setting a specified width for one using vw is probably a good choice. 
[Flexbox Unequal Width Columns](https://www.sitepoint.com/community/t/flexbox-unequal-width-columns/345934/2)
[Tailwind Flex CSS](https://tailwindcss.com/docs/flex)
<img width="775" alt="image" src="https://github.com/hack4impact-calpoly/slo-beaver-brigade/assets/109496618/ddd83f42-efaf-46cc-b557-c4595d63a596">

**Comment by Sohini-pillay** [comment]
I moved the events calendar title to the left, added the frontend for the filters, and moved the large calendar to the right side of the page, leaving some room on the bottom left for the mini calendar. I still have to move the next and back arrows for the main calendar and clean it up a bit!
