### ISSUE TITLE
Volunteer Hours Card 

### ISSUE THREAD

**Issue by javalosr2004** [hack4impact-calpoly/slo-beaver-brigade#87]
**Description**
Your task is to create a card on the dashboard for users to be able to view the total hours that they have volunteered, there are two portions to this, one is a simple card with just the total hours volunteered, and the next is a backside to the card with events volunteered and respective hours and date to the right of the event title.

**Acceptance Criteria**
Correctly retrieves sum of events volunteered, and actual events.

Steps:
- Create a VolunteerCard component; follow a similar format to flipped card component [here](https://www.w3schools.com/howto/howto_css_flip_card.asp).
- Get clerk-db id via useUser and fetching relevant data using `/api/user/[userId]`. More detail on this/ impelmentation can be found in the homepage of the react project (page.tsx).
- Parse the fetched data; simple for loop/reducer for total hours volunteered, I recommend fetching all events once via `/api/events,` and using that when going through the `eventsAttended` list, instead of continually calling `/api/events/[eventId]`. 
- Now just list out the eventsAttended, again with a map, I recommend using the [Chakra Table](https://chakra-ui.com/docs/components/table), for easier formatting.

**Additional Information**
<img width="878" alt="image" src="https://github.com/hack4impact-calpoly/slo-beaver-brigade/assets/109496618/388795f0-038c-472a-9ef7-15bb59817d63">
<img width="878" alt="image" src="https://github.com/hack4impact-calpoly/slo-beaver-brigade/assets/109496618/11b4dfe8-11c1-4e77-891c-f6976eac0142">
![IMG_4171](https://github.com/hack4impact-calpoly/slo-beaver-brigade/assets/109496618/6a8ee618-7ef5-4a3c-ba1d-de1d3928f302)

**Comment by tkim516** [comment]
Issue Updates:
- This page will be located in /admin/hours/
- By default, Total Volunteer Hours = event duration * number of attendees.
- Make sure to only count Total Volunteer Hours for Events that have the "volunteer" event type

- Create UI and functionality for the Date Range filter.
- ONLY create the UI for the Search Events filter (functionality will be a separate issue)

<img width="785" alt="Screenshot 2024-04-20 at 2 46 16 PM" src="https://github.com/hack4impact-calpoly/slo-beaver-brigade/assets/149984868/7113aefc-00ed-49a4-9df7-6904083909b5">
